[workspace]

members = [
    "nearby-connections-sys"
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.77.2"
license = "Apache-2.0"
repository = "https://github.com/google/nearby"
homepage = "https://github.com/google/nearby"
